# Generated by Django 5.2.9 on 2025-12-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeda_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city_pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
