# Generated by Django 5.2.9 on 2025-12-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xeda_backend', '0002_contact_city_pincode_alter_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
